title: Iris Tang
logo: /assets/img/logo_self.jpg
description: Iris Tang – Mechanical Engineering Portfolio
show_downloads: false
github:
  is_user_page: false
  is_project_page: false
theme: jekyll-theme-minimal
