defaults:
  -
    scope:
      path: ""
    values:
      styles: /assets/css/custom.css

title: Xinxuan Tang
description: Preferred Name: Iris
logo: /assets/img/logo_self.jpg
show_downloads: false
github:
  is_user_page: false
  is_project_page: false
theme: jekyll-theme-minimal
