title: Xinxuan Tang
description: >
  Mechanical Engineering Portfolio  
  Preferred Name: Iris
logo: "{{ '/assets/img/logo_self.jpg' | relative_url }}"
show_downloads: false
github:
  is_user_page: false
  is_project_page: false
url: "https://k2t2-314.github.io"
baseurl: "/Portfolio"
theme: jekyll-theme-minimal

defaults:
  -
    scope:
      path: ""
    values:
      styles: /assets/css/custom.css

